#!/usr/bin/env python3
"""Generate TypeScript model contracts from Pydantic; no third-party generator needed."""
import argparse
from pathlib import Path
from pydantic import BaseModel
from backend import models
from backend.cloud import contracts
ROOT=Path(__file__).resolve().parents[1]
def render(s):
    if '$ref' in s: return s['$ref'].split('/')[-1]
    if 'const' in s: return repr(s['const']).lower() if isinstance(s['const'],bool) else repr(s['const'])
    if 'enum' in s: return ' | '.join(repr(x) for x in s['enum'])
    if 'anyOf' in s: return ' | '.join(render(x) for x in s['anyOf'])
    t=s.get('type')
    if t=='array': return f"Array<{render(s.get('items',{}))}>"
    if t=='object':
        if 'properties' in s: return '{ '+ '; '.join(f'{k}: {render(v)}' for k,v in s['properties'].items())+' }'
        a=s.get('additionalProperties',True)
        return 'Record<string, '+(render(a) if isinstance(a,dict) else 'unknown')+'>'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(t,'unknown')
def generate():
    definitions={}
    for module in (models,contracts):
        for name,model in vars(module).items():
            if isinstance(model,type) and issubclass(model,BaseModel) and model not in (BaseModel,contracts.StrictModel):
                schema=model.model_json_schema(mode='serialization');definitions.update(schema.pop('$defs',{}));definitions[name]=schema
    content='// Generated by python -m scripts.generate_contracts. Do not edit.\n\n'
    for name,schema in sorted(definitions.items()): content+=f'export type {name} = {render(schema)};\n\n'
    content+="export type RequirementStatus = Requirement['status'];\nexport type RequirementKind = Requirement['kind'];\nexport type CheckStatus = GraduationCheck['status'];\n"
    return content
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    dest=ROOT/'frontend/lib/api.ts';content=generate()
    if args.check:
        if dest.read_text()!=content: raise SystemExit('Contracts are stale. Run python -m scripts.generate_contracts.')
        print('Contracts match backend models.')
    else: dest.write_text(content)
