// Generated by python -m scripts.generate_contracts. Do not edit.

export type AccountSummary = { id: number; email: string; created_at: string; verified: boolean };

export type AdvisoryNote = { id: string; program: string; severity: 'applied' | 'confirm' | 'sequencing' | 'cap'; courses: Array<string>; source: string; title: string; detail: string };

export type AnalysisResponse = { audits: Array<MajorAudit>; readiness: GraduationReadiness; completed_courses: Array<CourseRecord>; in_progress_courses: Array<CourseRecord>; overlaps: Array<OverlapOpportunity>; recommendations: Array<Recommendation>; premed: PremedSummary; plan: PlanResult; advisories: Array<AdvisoryNote>; scenario_id: number | null; warnings: Array<string>; processing_ms: number };

export type AuditInventoryResponse = { folder: string; audits: Array<AuditRecord>; latest: Array<AuditRecord>; warnings: Array<string> };

export type AuditRecord = { filename: string; program_code: string; program_name: string; prepared_on: string | null; prepared_on_label: string; catalog_year: string; dated_from: string; is_latest: boolean };

export type AuditSnapshot = { program_code: string; program_name: string; prepared_on: string | null; source_filename: string };

export type AuditSummary = { earned_hours: number | null; in_progress_hours: number; gpa: number | null; catalog_year: string | null; complete_requirements: number; in_progress_requirements: number; remaining_requirements: number; remaining_specific_credits: number };

export type AuthSession = { account: AccountSummary; token: string; expires_at: string; adopted_scenarios: number; message: string };

export type AuthStatus = { signed_in: boolean; account: AccountSummary | null; accounts_exist: boolean; email_verification: boolean; min_passphrase_length: number };

export type CourseRecord = { code: string; term: string; campus: string; subject: string; number: string; credits: number; grade: string; title: string; status: 'complete' | 'in_progress' | 'not_completed' };

export type CreatePlan = { audit_id: string; name: string; preferences: Preferences };

export type CustomCourse = { course_id: string; code: string; label: string; credits: number; term: string; majors: Array<string>; note: string };

export type DemoResponse = { available: boolean; files: Array<string> };

export type FileSpec = { size: number };

export type GraduationCheck = { id: string; label: string; status: 'pass' | 'note' | 'gap'; detail: string; evidence: Array<string> };

export type GraduationReadiness = { status: 'on_track' | 'on_track_with_notes' | 'blocked'; graduation_term: string; pass_count: number; note_count: number; gap_count: number; checks: Array<GraduationCheck> };

export type JobSummary = { id: string; status: 'awaiting_upload' | 'queued' | 'processing' | 'completed' | 'failed' | 'cancelled'; created_at: string; error: string | null; plan_id: string | null; stage: string | null; progress: number };

export type LoginRequest = { email: string; passphrase: string };

export type MajorAudit = { program_code: string; prepared_on: string; campus: string; name: string; source_file: string; official_majors: Array<string>; summary: AuditSummary; requirements: Array<Requirement>; warnings: Array<string> };

export type OverlapOpportunity = { course_code: string; majors: Array<string>; requirement_ids: Array<string>; requirement_names: Array<string>; potential_credits: number; reason: string };

export type PersonalRules = { finance_sequence: boolean; finance_equivalence: boolean; dance: boolean };

export type PlaceholderChoice = { slot_id: string; course_code: string; requirement_id: string; note: string };

export type Placement = { course_id: string; course_code: string; term: string; credits: number; locked: boolean };

export type PlanPace = { outstanding_credits: number; open_terms: number; required_per_term: number; credit_ceiling: number; unplaced_credits: number; feasible: boolean };

export type PlanResult = { start_term: string; graduation_term: string; semesters: Array<SemesterPlan>; planned_credits: number; min_credits: number; applied_decisions: number; unplanned_requirements: Array<string>; pace: PlanPace; warnings: Array<string> };

export type PlanState = { placements: Array<Placement>; placeholders: Array<PlaceholderChoice>; term_settings: Array<TermSetting>; custom_courses: Array<CustomCourse>; removed_course_ids: Array<string> };

export type PlanSummary = { schema_version: number; graduation_term: string; start_term: string; term_count: number; planned_credits: number; course_count: number; placeholder_count: number; unplaced_count: number; heaviest_term_credits: number; lightest_term_credits: number; programs: Array<string>; readiness_status: string; gap_count: number; warning_count: number; premed: boolean; mcat_terms: Array<string>; mcat_credit_ceiling: number; mcat_course_ceiling: number; credits_per_term: number; min_credits: number; include_summer: boolean; personal_rules: Record<string, boolean> };

export type PlannedCourse = { id: string; code: string; subject: string; catalog_number: string; label: string; credits: number; majors: Array<string>; requirement_ids: Array<string>; is_placeholder: boolean; status: 'planned' | 'in_progress' | 'personal' | 'premed' | 'milestone'; movable: boolean; prerequisites: Array<string>; corequisites: Array<string>; alternatives: Array<string>; attributes: Array<string>; advisories: Array<string>; justification: string; sequenced_by: string; class_search_url: string; resolved_from_placeholder: boolean; note: string };

export type Preferences = { premed: boolean; start_term: string; graduation_term: string; credits_per_term: number; min_credits: number; include_summer: boolean; term_credit_limits: Record<string, number>; term_course_limits: Record<string, number>; mcat_terms: Array<string>; mcat_credit_ceiling: number; mcat_course_ceiling: number; course_ceiling: number; personal_rules: PersonalRules; recurring_commitment: RecurringCommitment };

export type PremedRequirement = { id: string; name: string; detail: string; status: 'complete' | 'in_progress' | 'remaining'; required: boolean; completed_courses: Array<string>; in_progress_courses: Array<string>; remaining_courses: Array<string>; note: string };

export type PremedSummary = { framework: string; complete_count: number; in_progress_count: number; remaining_count: number; requirements: Array<PremedRequirement>; sources: Array<Record<string, string>> };

export type ProfileUpdate = { preferences: Preferences };

export type Recommendation = { course_code: string; subject: string; catalog_number: string; majors: Array<string>; requirement_ids: Array<string>; requirement_names: Array<string>; credits: number; priority: number; reason: string; alternatives: Array<string>; class_search_url: string };

export type RecurringCommitment = { enabled: boolean; label: string; code: string; credits: number; include_summer: boolean };

export type RegisterRequest = { email: string; passphrase: string };

export type RegisterResult = { status: 'registered' | 'verification_sent'; email: string; message: string; session: AuthSession | null };

export type Requirement = { id: string; major: string; section: string; name: string; kind: 'course' | 'elective' | 'milestone' | 'gpa' | 'project'; status: 'complete' | 'in_progress' | 'remaining'; credits_required: number; credits_earned: number; credits_in_progress: number; credits_remaining: number; course_options: Array<string>; courses_completed: Array<string>; courses_in_progress: Array<string>; criteria: Array<string>; exclusions: Array<string>; source_text: string; confidence: number; satisfied_by: string; source_label: string; source_pages: Array<number>; parent_id: string | null; logic: 'all' | 'any' | 'unknown'; minimum_grade: string; needs_review: boolean };

export type SavePlan = { revision: number; state: PlanState; name: string | null };

export type Scenario = { id: number; name: string; created_at: string; updated_at: string; start_term: string; graduation_term: string; options: Record<string, unknown>; placements: Array<Placement>; placeholders: Array<PlaceholderChoice>; term_settings: Array<TermSetting>; custom_courses: Array<CustomCourse>; removed_course_ids: Array<string>; audits: Array<AuditSnapshot>; stale_audit_warnings: Array<string> };

export type ScenarioCreate = { name: string; start_term: string; graduation_term: string; options: Record<string, unknown> };

export type ScenarioSummary = { id: number; name: string; created_at: string; updated_at: string; start_term: string; graduation_term: string; options: Record<string, unknown> };

export type ScenarioUpdate = { name: string | null; start_term: string | null; graduation_term: string | null; options: Record<string, unknown> | null };

export type SemesterPlan = { term: string; term_code: string; courses: Array<PlannedCourse>; total_credits: number; credit_limit: number; course_limit: number; min_credits: number; is_mcat_term: boolean; is_in_progress: boolean; is_unplaced: boolean; note: string };

export type StartAnalysis = { job_id: string };

export type TermSetting = { term: string; credit_limit: number; is_mcat_term: boolean; note: string };

export type UploadRequest = { files: Array<FileSpec>; preferences: Preferences; consent: true };

export type UploadTicket = { job_id: string; uploads: Array<Record<string, string>> };

export type VerifyRequest = { email: string; code: string };

export type RequirementStatus = Requirement['status'];
export type RequirementKind = Requirement['kind'];
export type CheckStatus = GraduationCheck['status'];
